require:
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/RepeatedDescription:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
